# ProGuard rules for Flutter app
# Keep Flutter engine and plugins
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.** { *; }
-keep class io.flutter.embedding.engine.** { *; }
-keep class io.flutter.embedding.android.** { *; }

# Keep native methods
-keepclasseswithmembernames class * {
    native <methods>;
}

# Keep JS interface methods
-keepclassmembers class * {
    @android.webkit.JavascriptInterface <methods>;
}

# Don't warn about Flutter classes
-dontwarn io.flutter.embedding.engine.**

# Add any rules for libraries that require them here
# Example: keep Gson model classes if using reflection-based serialization

## Rules added to address R8 missing classes during release minification
# Suppress warnings generated by Android Gradle plugin for Play Core splitcompat
-dontwarn com.google.android.play.core.splitcompat.SplitCompatApplication

# Keep Play Core splitcompat classes (avoid R8 stripping them)
-keep class com.google.android.play.core.splitcompat.** { *; }

# Keep Flutter Play Store split integration class if present
-keep class io.flutter.embedding.android.FlutterPlayStoreSplitApplication { *; }
-dontwarn io.flutter.embedding.android.FlutterPlayStoreSplitApplication

